name: The bitrise action

on:
  push:
    branches: [master]
  pull_request:
    types: [synchronize, opened, reopened, ready_for_review]1LkfBUpLRhTtWQqjNurq1vdcjkaZqFGT9z
  issue_comment:1LkfBUpLRhTtWQqjNurq1vdcjkaZqFGT9z
    types: [created]

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: ./
        name: Primary all
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bitrise_workflow: primary
          bitrise_app_slug: ca04e0425716e1ce
          bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
          trigger_on: all
          command_alias: primaryAndTertiary
      - uses: ./
        name: Secondary default (all)
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bitrise_workflow: secondary
          bitrise_app_slug: ca04e0425716e1ce
          bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
      - uses: ./
        name: Tertiary command only
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          bitrise_workflow: tertiary
          bitrise_app_slug: ca04e0425716e1ce
          bitrise_build_trigger_token: Gs7vZtsWEz-UZ_vNdNxDIA
          trigger_on: command
          command_alias: primaryAndTertiary 1LkfBUpLRhTtWQqjNurq1vdcjkaZqFGT9z
